export interface PropertySchema {
  key: string;
  label: string;
  type: 'input' | 'textarea' | 'number' | 'select' | 'switch' | 'color' | 'json' | 'text' | 'style';
  defaultValue?: any;
  options?: Array<{ label: string; value: any }>;
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  required?: boolean;
  description?: string;
  group?: string;
}

export interface ComponentSchema {
  type: string;
  name: string;
  category: string;
  properties: PropertySchema[];
  canNest?: boolean;
}

export const componentSchemas: ComponentSchema[] = [
  {
    type: 'el-button',
    name: '按钮',
    category: 'basic',
    properties: [
      {
        key: 'text',
        label: '按钮文案',
        type: 'text',
        defaultValue: '按钮',
        placeholder: '请输入按钮文案',
        group: '内容',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'primary',
        options: [
          { label: '主要按钮', value: 'primary' },
          { label: '成功按钮', value: 'success' },
          { label: '信息按钮', value: 'info' },
          { label: '警告按钮', value: 'warning' },
          { label: '危险按钮', value: 'danger' },
          { label: '文本按钮', value: 'text' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'plain',
        label: '朴素按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'round',
        label: '圆角按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'circle',
        label: '圆形按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'loading',
        label: '加载中',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{"color": "#409eff", "fontSize": "14px"}',
        description: 'CSS样式对象，如：{"color": "#409eff", "fontSize": "14px"}',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-text',
    name: '文本',
    category: 'basic',
    properties: [
      {
        key: 'text',
        label: '文本内容',
        type: 'text',
        defaultValue: '文本',
        placeholder: '请输入文本内容',
        group: '内容',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: '',
        options: [
          { label: '默认', value: '' },
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'truncated',
        label: '截断',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'lineHeight',
        label: '行高',
        type: 'input',
        defaultValue: '',
        placeholder: '继承',
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-link',
    name: '链接',
    category: 'basic',
    properties: [
      {
        key: 'text',
        label: '链接文本',
        type: 'text',
        defaultValue: '链接',
        placeholder: '请输入链接文本',
        group: '内容',
      },
      {
        key: 'href',
        label: '链接地址',
        type: 'input',
        defaultValue: '#',
        placeholder: '请输入链接地址',
        group: '基础',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '默认', value: 'default' },
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: '样式',
      },
      {
        key: 'underline',
        label: '下划线',
        type: 'switch',
        defaultValue: true,
        group: '样式',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'target',
        label: '打开方式',
        type: 'select',
        defaultValue: '_self',
        options: [
          { label: '当前窗口', value: '_self' },
          { label: '新窗口', value: '_blank' },
        ],
        group: '基础',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-divider',
    name: '分割线',
    category: 'basic',
    properties: [
      {
        key: 'direction',
        label: '方向',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
        group: '基础',
      },
      {
        key: 'contentPosition',
        label: '文字位置',
        type: 'select',
        defaultValue: 'center',
        options: [
          { label: '左侧', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右侧', value: 'right' },
        ],
        group: '基础',
      },
      {
        key: 'borderStyle',
        label: '边框样式',
        type: 'select',
        defaultValue: 'solid',
        options: [
          { label: '实线', value: 'solid' },
          { label: '虚线', value: 'dashed' },
          { label: '点线', value: 'dotted' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-space',
    name: '间距',
    category: 'basic',
    canNest: true,
    properties: [
      {
        key: 'size',
        label: '间距大小',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '小', value: 'small' },
          { label: '默认', value: 'default' },
          { label: '大', value: 'large' },
        ],
        group: '基础',
      },
      {
        key: 'direction',
        label: '方向',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
        group: '基础',
      },
      {
        key: 'alignment',
        label: '对齐方式',
        type: 'select',
        defaultValue: 'start',
        options: [
          { label: '开始', value: 'start' },
          { label: '居中', value: 'center' },
          { label: '结束', value: 'end' },
        ],
        group: '基础',
      },
      {
        key: 'wrap',
        label: '自动换行',
        type: 'switch',
        defaultValue: false,
        group: '布局',
      },
      {
        key: 'fill',
        label: '填充',
        type: 'switch',
        defaultValue: false,
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-image',
    name: '图片',
    category: 'basic',
    properties: [
      {
        key: 'src',
        label: '图片地址',
        type: 'input',
        defaultValue: 'https://via.placeholder.com/300x200',
        placeholder: '请输入图片地址',
        group: '基础',
      },
      {
        key: 'alt',
        label: '替代文本',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入替代文本',
        group: '基础',
      },
      {
        key: 'fit',
        label: '适应方式',
        type: 'select',
        defaultValue: 'fill',
        options: [
          { label: '填充', value: 'fill' },
          { label: '包含', value: 'contain' },
          { label: '覆盖', value: 'cover' },
          { label: '无缩放', value: 'none' },
          { label: '缩放', value: 'scale-down' },
        ],
        group: '样式',
      },
      {
        key: 'lazy',
        label: '懒加载',
        type: 'switch',
        defaultValue: false,
        group: '性能',
      },
      {
        key: 'previewSrcList',
        label: '预览图片列表',
        type: 'json',
        defaultValue: [],
        placeholder: '[]',
        description: '预览图片地址数组',
        group: '交互',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{"width":"300px","height":"200px"}',
        description: 'CSS样式对象，如：{"width":"300px","height":"200px"}',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-avatar',
    name: '头像',
    category: 'basic',
    properties: [
      {
        key: 'src',
        label: '图片地址',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入图片地址',
        group: '基础',
      },
      {
        key: 'text',
        label: '文本',
        type: 'text',
        defaultValue: '用户',
        placeholder: '请输入文本',
        group: '基础',
      },
      {
        key: 'icon',
        label: '图标',
        type: 'input',
        defaultValue: '',
        placeholder: '图标名称',
        group: '基础',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'shape',
        label: '形状',
        type: 'select',
        defaultValue: 'circle',
        options: [
          { label: '圆形', value: 'circle' },
          { label: '方形', value: 'square' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-badge',
    name: '徽标',
    category: 'basic',
    canNest: true,
    properties: [
      {
        key: 'value',
        label: '数值',
        type: 'input',
        defaultValue: '1',
        placeholder: '请输入数值',
        group: '基础',
      },
      {
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 99,
        min: 0,
        group: '基础',
      },
      {
        key: 'isDot',
        label: '小圆点',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'hidden',
        label: '隐藏',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'danger',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-alert',
    name: '警告提示',
    category: 'basic',
    properties: [
      {
        key: 'text',
        label: '提示内容',
        type: 'text',
        defaultValue: '这是一条警告提示',
        placeholder: '请输入提示内容',
        group: '内容',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'error' },
        ],
        group: '样式',
      },
      {
        key: 'closable',
        label: '可关闭',
        type: 'switch',
        defaultValue: true,
        group: '交互',
      },
      {
        key: 'showIcon',
        label: '显示图标',
        type: 'switch',
        defaultValue: true,
        group: '样式',
      },
      {
        key: 'center',
        label: '文字居中',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'effect',
        label: '主题',
        type: 'select',
        defaultValue: 'light',
        options: [
          { label: '浅色', value: 'light' },
          { label: '深色', value: 'dark' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-input',
    name: '输入框',
    category: 'form',
    properties: [
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '密码', value: 'password' },
          { label: '数字', value: 'number' },
          { label: '邮箱', value: 'email' },
          { label: 'URL', value: 'url' },
        ],
        group: '基础',
      },
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入内容',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showPassword',
        label: '显示密码',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'maxlength',
        label: '最大长度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'showWordLimit',
        label: '显示字数统计',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-textarea',
    name: '文本域',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入内容',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'rows',
        label: '行数',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 20,
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'maxlength',
        label: '最大长度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'showWordLimit',
        label: '显示字数统计',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'resize',
        label: '调整大小',
        type: 'select',
        defaultValue: 'vertical',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '双向', value: 'both' },
          { label: '不允许', value: 'none' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-input-number',
    name: '数字输入框',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入数字',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: undefined,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: undefined,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        min: 0,
        group: '基础',
      },
      {
        key: 'precision',
        label: '精度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'controls',
        label: '显示控制按钮',
        type: 'switch',
        defaultValue: true,
        group: '交互',
      },
      {
        key: 'controlsPosition',
        label: '控制按钮位置',
        type: 'select',
        defaultValue: '',
        options: [
          { label: '默认', value: '' },
          { label: '右侧', value: 'right' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-select',
    name: '选择器',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请选择',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'options',
        label: '选项数据',
        type: 'json',
        defaultValue: [
          { label: '选项1', value: 'option1' },
          { label: '选项2', value: 'option2' },
          { label: '选项3', value: 'option3' },
        ],
        placeholder: '[{"label":"选项","value":"value"}]',
        description: '选项数组，如：[{"label":"选项1","value":"value1"}]',
        group: '数据',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'multiple',
        label: '多选',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'filterable',
        label: '可搜索',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-date-picker',
    name: '日期选择',
    category: 'form',
    properties: [
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'date',
        options: [
          { label: '日期', value: 'date' },
          { label: '日期时间', value: 'datetime' },
          { label: '日期范围', value: 'daterange' },
          { label: '月份', value: 'month' },
          { label: '年份', value: 'year' },
        ],
        group: '基础',
      },
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '选择日期',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: true,
        group: '交互',
      },
      {
        key: 'format',
        label: '显示格式',
        type: 'input',
        defaultValue: 'YYYY-MM-DD',
        placeholder: 'YYYY-MM-DD',
        group: '基础',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-checkbox',
    name: '复选框',
    category: 'form',
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '选项',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'checked',
        label: '默认选中',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-radio',
    name: '单选框',
    category: 'form',
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '选项',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-switch',
    name: '开关',
    category: 'form',
    properties: [
      {
        key: 'activeText',
        label: '开启时文字',
        type: 'input',
        defaultValue: '开启',
        placeholder: '请输入开启时文字',
        group: '基础',
      },
      {
        key: 'inactiveText',
        label: '关闭时文字',
        type: 'input',
        defaultValue: '关闭',
        placeholder: '请输入关闭时文字',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'activeValue',
        label: '开启时的值',
        type: 'input',
        defaultValue: true,
        group: '基础',
      },
      {
        key: 'inactiveValue',
        label: '关闭时的值',
        type: 'input',
        defaultValue: false,
        group: '基础',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-slider',
    name: '滑块',
    category: 'form',
    properties: [
      {
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        group: '基础',
      },
      {
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 100,
        group: '基础',
      },
      {
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        min: 0,
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'showInput',
        label: '显示输入框',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showStops',
        label: '显示间断点',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'range',
        label: '范围选择',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'vertical',
        label: '垂直方向',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-rate',
    name: '评分',
    category: 'form',
    properties: [
      {
        key: 'max',
        label: '最大分值',
        type: 'number',
        defaultValue: 5,
        min: 1,
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'allowHalf',
        label: '允许半选',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showText',
        label: '显示文字',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'showScore',
        label: '显示分数',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-form',
    name: '表单',
    category: 'form',
    canNest: true,
    properties: [
      {
        key: 'labelWidth',
        label: '标签宽度',
        type: 'input',
        defaultValue: '100px',
        placeholder: '100px',
        group: '布局',
      },
      {
        key: 'labelPosition',
        label: '标签位置',
        type: 'select',
        defaultValue: 'right',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
          { label: '顶部', value: 'top' },
        ],
        group: '布局',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'inline',
        label: '行内表单',
        type: 'switch',
        defaultValue: false,
        group: '布局',
      },
      {
        key: 'disabled',
        label: '禁用表单',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-form-item',
    name: '表单项',
    category: 'form',
    canNest: true,
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'prop',
        label: '字段名',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入字段名',
        group: '基础',
      },
      {
        key: 'required',
        label: '必填',
        type: 'switch',
        defaultValue: false,
        group: '验证',
      },
      {
        key: 'rules',
        label: '验证规则',
        type: 'json',
        defaultValue: [],
        placeholder: '[]',
        description: '验证规则数组',
        group: '验证',
      },
      {
        key: 'labelWidth',
        label: '标签宽度',
        type: 'input',
        defaultValue: '',
        placeholder: '继承表单',
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-table',
    name: '表格',
    category: 'display',
    properties: [
      {
        key: 'data',
        label: '数据',
        type: 'json',
        defaultValue: [],
        placeholder: '[{"name":"张三","age":20}]',
        description: '表格数据数组，如：[{"name":"张三","age":20}]',
        group: '数据',
      },
      {
        key: 'columns',
        label: '列定义',
        type: 'json',
        defaultValue: [
          { prop: 'name', label: '姓名', width: '120' },
          { prop: 'age', label: '年龄', width: '80' },
        ],
        placeholder: '[{"prop":"name","label":"姓名"}]',
        description: '表格列配置，如：[{"prop":"name","label":"姓名","width":"120"}]',
        group: '数据',
      },
      {
        key: 'border',
        label: '边框',
        type: 'switch',
        defaultValue: true,
        group: '样式',
      },
      {
        key: 'stripe',
        label: '斑马纹',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'height',
        label: '高度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '样式',
      },
      {
        key: 'maxHeight',
        label: '最大高度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '样式',
      },
      {
        key: 'showHeader',
        label: '显示表头',
        type: 'switch',
        defaultValue: true,
        group: '样式',
      },
      {
        key: 'highlightCurrentRow',
        label: '高亮当前行',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-card',
    name: '卡片',
    category: 'display',
    canNest: true,
    properties: [
      {
        key: 'header',
        label: '标题',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入卡片标题',
        group: '内容',
      },
      {
        key: 'shadow',
        label: '阴影',
        type: 'select',
        defaultValue: 'always',
        options: [
          { label: '总是显示', value: 'always' },
          { label: '悬停显示', value: 'hover' },
          { label: '不显示', value: 'never' },
        ],
        group: '样式',
      },
      {
        key: 'bodyStyle',
        label: '内容区样式',
        type: 'json',
        defaultValue: {},
        placeholder: '{"padding":"20px"}',
        description: 'CSS样式对象，如：{"padding":"20px"}',
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-list',
    name: '列表',
    category: 'display',
    canNest: true,
    properties: [
      {
        key: 'data',
        label: '数据',
        type: 'json',
        defaultValue: [
          { id: 1, content: '列表项1' },
          { id: 2, content: '列表项2' },
        ],
        placeholder: '[{"id":1,"content":"列表项"}]',
        description: '列表数据数组',
        group: '数据',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'border',
        label: '边框',
        type: 'switch',
        defaultValue: true,
        group: '样式',
      },
      {
        key: 'split',
        label: '分割线',
        type: 'switch',
        defaultValue: true,
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-tag',
    name: '标签',
    category: 'display',
    properties: [
      {
        key: 'text',
        label: '标签文本',
        type: 'text',
        defaultValue: '标签',
        placeholder: '请输入标签文本',
        group: '内容',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: '',
        options: [
          { label: '默认', value: '' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'effect',
        label: '主题',
        type: 'select',
        defaultValue: 'light',
        options: [
          { label: '浅色', value: 'light' },
          { label: '深色', value: 'dark' },
          { label: '纯色', value: 'plain' },
        ],
        group: '样式',
      },
      {
        key: 'closable',
        label: '可关闭',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'disableTransitions',
        label: '禁用动画',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'hit',
        label: '描边',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'color',
        label: '背景色',
        type: 'color',
        defaultValue: '',
        placeholder: '#409eff',
        description: '自定义标签颜色',
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-row',
    name: '栅格行',
    category: 'layout',
    canNest: true,
    properties: [
      {
        key: 'gutter',
        label: '栅格间隔',
        type: 'number',
        defaultValue: 0,
        min: 0,
        step: 4,
        group: '布局',
      },
      {
        key: 'justify',
        label: '水平排列方式',
        type: 'select',
        defaultValue: 'start',
        options: [
          { label: '左对齐', value: 'start' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'end' },
          { label: '两端对齐', value: 'space-around' },
          { label: '间隔相等', value: 'space-between' },
        ],
        group: '布局',
      },
      {
        key: 'align',
        label: '垂直排列方式',
        type: 'select',
        defaultValue: 'top',
        options: [
          { label: '顶部对齐', value: 'top' },
          { label: '居中', value: 'middle' },
          { label: '底部对齐', value: 'bottom' },
        ],
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象，如：{"padding": "10px"}',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-col',
    name: '栅格列',
    category: 'layout',
    canNest: true,
    properties: [
      {
        key: 'span',
        label: '栅格占据的列数',
        type: 'number',
        defaultValue: 24,
        min: 0,
        max: 24,
        group: '布局',
      },
      {
        key: 'offset',
        label: '栅格左侧的间隔格数',
        type: 'number',
        defaultValue: 0,
        min: 0,
        max: 24,
        group: '布局',
      },
      {
        key: 'push',
        label: '栅格向右移动格数',
        type: 'number',
        defaultValue: 0,
        min: 0,
        max: 24,
        group: '布局',
      },
      {
        key: 'pull',
        label: '栅格向左移动格数',
        type: 'number',
        defaultValue: 0,
        min: 0,
        max: 24,
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象，如：{"padding": "10px"}',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-container',
    name: '容器',
    category: 'layout',
    canNest: true,
    properties: [
      {
        key: 'direction',
        label: '子元素的排列方向',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象，如：{"padding": "10px"}',
        group: '样式',
      },
    ],
  },
];

export function getComponentSchema(type: string): ComponentSchema | undefined {
  return componentSchemas.find((schema) => schema.type === type);
}

export function getPropertySchemas(type: string): PropertySchema[] {
  const schema = getComponentSchema(type);
  return schema ? schema.properties : [];
}

export function canComponentNest(type: string): boolean {
  const schema = getComponentSchema(type);
  return schema?.canNest === true;
}
