export interface PropertySchema {
  key: string;
  label: string;
  type: 'input' | 'textarea' | 'number' | 'select' | 'switch' | 'color' | 'json' | 'text' | 'style';
  defaultValue?: any;
  options?: Array<{ label: string; value: any }>;
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  required?: boolean;
  description?: string;
  group?: string;
}

export interface ComponentSchema {
  type: string;
  name: string;
  category: string;
  properties: PropertySchema[];
  canNest?: boolean;
}

export const componentSchemas: ComponentSchema[] = [
  {
    type: 'el-form',
    name: '表单',
    category: 'form',
    canNest: true,
    properties: [
      {
        key: 'labelWidth',
        label: '标签宽度',
        type: 'input',
        defaultValue: '100px',
        placeholder: '100px',
        group: '布局',
      },
      {
        key: 'labelPosition',
        label: '标签位置',
        type: 'select',
        defaultValue: 'right',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
          { label: '顶部', value: 'top' },
        ],
        group: '布局',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'inline',
        label: '行内表单',
        type: 'switch',
        defaultValue: false,
        group: '布局',
      },
      {
        key: 'disabled',
        label: '禁用表单',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-form-item',
    name: '表单项',
    category: 'form',
    canNest: true,
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'prop',
        label: '字段名',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入字段名',
        group: '基础',
      },
      {
        key: 'required',
        label: '必填',
        type: 'switch',
        defaultValue: false,
        group: '验证',
      },
      {
        key: 'rules',
        label: '验证规则',
        type: 'json',
        defaultValue: [],
        placeholder: '[]',
        description: '验证规则数组',
        group: '验证',
      },
      {
        key: 'labelWidth',
        label: '标签宽度',
        type: 'input',
        defaultValue: '',
        placeholder: '继承表单',
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-input',
    name: '输入框',
    category: 'form',
    properties: [
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '密码', value: 'password' },
          { label: '数字', value: 'number' },
          { label: '邮箱', value: 'email' },
          { label: 'URL', value: 'url' },
        ],
        group: '基础',
      },
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入内容',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showPassword',
        label: '显示密码',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'maxlength',
        label: '最大长度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'showWordLimit',
        label: '显示字数统计',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-input-number',
    name: '数字输入框',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入数字',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: undefined,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: undefined,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        min: 0,
        group: '基础',
      },
      {
        key: 'precision',
        label: '精度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'controls',
        label: '显示控制按钮',
        type: 'switch',
        defaultValue: true,
        group: '交互',
      },
      {
        key: 'controlsPosition',
        label: '控制按钮位置',
        type: 'select',
        defaultValue: '',
        options: [
          { label: '默认', value: '' },
          { label: '右侧', value: 'right' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-select',
    name: '选择器',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请选择',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'options',
        label: '选项数据',
        type: 'json',
        defaultValue: [
          { label: '选项1', value: 'option1' },
          { label: '选项2', value: 'option2' },
          { label: '选项3', value: 'option3' },
        ],
        placeholder: '[{"label":"选项","value":"value"}]',
        description: '选项数组，如：[{"label":"选项1","value":"value1"}]',
        group: '数据',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'multiple',
        label: '多选',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'filterable',
        label: '可搜索',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-date-picker',
    name: '日期选择',
    category: 'form',
    properties: [
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'date',
        options: [
          { label: '日期', value: 'date' },
          { label: '日期时间', value: 'datetime' },
          { label: '日期范围', value: 'daterange' },
          { label: '月份', value: 'month' },
          { label: '年份', value: 'year' },
        ],
        group: '基础',
      },
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '选择日期',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: true,
        group: '交互',
      },
      {
        key: 'format',
        label: '显示格式',
        type: 'input',
        defaultValue: 'YYYY-MM-DD',
        placeholder: 'YYYY-MM-DD',
        group: '基础',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-checkbox',
    name: '复选框',
    category: 'form',
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '选项',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'checked',
        label: '默认选中',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-radio',
    name: '单选框',
    category: 'form',
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '选项',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-switch',
    name: '开关',
    category: 'form',
    properties: [
      {
        key: 'activeText',
        label: '开启时文字',
        type: 'input',
        defaultValue: '开启',
        placeholder: '请输入开启时文字',
        group: '基础',
      },
      {
        key: 'inactiveText',
        label: '关闭时文字',
        type: 'input',
        defaultValue: '关闭',
        placeholder: '请输入关闭时文字',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'activeValue',
        label: '开启时的值',
        type: 'input',
        defaultValue: true,
        group: '基础',
      },
      {
        key: 'inactiveValue',
        label: '关闭时的值',
        type: 'input',
        defaultValue: false,
        group: '基础',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-slider',
    name: '滑块',
    category: 'form',
    properties: [
      {
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        group: '基础',
      },
      {
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 100,
        group: '基础',
      },
      {
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        min: 0,
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'showInput',
        label: '显示输入框',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showStops',
        label: '显示间断点',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'range',
        label: '范围选择',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'vertical',
        label: '垂直方向',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-rate',
    name: '评分',
    category: 'form',
    properties: [
      {
        key: 'max',
        label: '最大分值',
        type: 'number',
        defaultValue: 5,
        min: 1,
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'allowHalf',
        label: '允许半选',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showText',
        label: '显示文字',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'showScore',
        label: '显示分数',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
  {
    type: 'el-button',
    name: '按钮',
    category: 'form',
    properties: [
      {
        key: 'text',
        label: '按钮文案',
        type: 'text',
        defaultValue: '按钮',
        placeholder: '请输入按钮文案',
        group: '内容',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'primary',
        options: [
          { label: '主要按钮', value: 'primary' },
          { label: '成功按钮', value: 'success' },
          { label: '信息按钮', value: 'info' },
          { label: '警告按钮', value: 'warning' },
          { label: '危险按钮', value: 'danger' },
          { label: '文本按钮', value: 'text' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'plain',
        label: '朴素按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'round',
        label: '圆角按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'circle',
        label: '圆形按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'loading',
        label: '加载中',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{"color": "#409eff", "fontSize": "14px"}',
        description: 'CSS样式对象，如：{"color": "#409eff", "fontSize": "14px"}',
        group: '样式',
      },
    ],
  },
];

export function getComponentSchema(type: string): ComponentSchema | undefined {
  return componentSchemas.find((schema) => schema.type === type);
}

export function getPropertySchemas(type: string): PropertySchema[] {
  const schema = getComponentSchema(type);
  return schema ? schema.properties : [];
}

export function canComponentNest(type: string): boolean {
  const schema = getComponentSchema(type);
  return schema?.canNest === true;
}

export function getChildComponentName(parentType: string, propKey: string): string {
  const childComponentMap: Record<string, Record<string, string>> = {
    'el-select': {
      options: 'el-option',
    },
  };

  return childComponentMap[parentType]?.[propKey] || '';
}
