export default [
  {
    type: 'el-button',
    name: '按钮',
    category: 'form',
    properties: [
      {
        key: 'content',
        label: '按钮文案',
        type: 'content',
        defaultValue: '按钮',
        placeholder: '请输入按钮文案',
        group: '内容',
      },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'primary',
        options: [
          { label: '主要按钮', value: 'primary' },
          { label: '成功按钮', value: 'success' },
          { label: '信息按钮', value: 'info' },
          { label: '警告按钮', value: 'warning' },
          { label: '危险按钮', value: 'danger' },
          { label: '文本按钮', value: 'text' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'plain',
        label: '朴素按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'round',
        label: '圆角按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'circle',
        label: '圆形按钮',
        type: 'switch',
        defaultValue: false,
        group: '样式',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'loading',
        label: '加载中',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{"color": "#409eff", "fontSize": "14px"}',
        description: 'CSS样式对象，如：{"color": "#409eff", "fontSize": "14px"}',
        group: '样式',
      },
    ],
  },
];
