export default [
  {
    type: 'el-form-item',
    name: '表单项',
    category: 'form',
    canNest: true,
    properties: [
      {
        key: 'label',
        label: '标签',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入标签文本',
        group: '基础',
      },
      {
        key: 'prop',
        label: '字段名',
        type: 'input',
        defaultValue: '',
        placeholder: '请输入字段名',
        group: '基础',
      },
      {
        key: 'required',
        label: '必填',
        type: 'switch',
        defaultValue: false,
        group: '验证',
      },
      {
        key: 'rules',
        label: '验证规则',
        type: 'json',
        defaultValue: [],
        placeholder: '[]',
        description: '验证规则数组',
        group: '验证',
      },
      {
        key: 'labelWidth',
        label: '标签宽度',
        type: 'input',
        defaultValue: '',
        placeholder: '继承表单',
        group: '布局',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
];
