export default [
  {
    type: 'el-input-number',
    name: '数字输入框',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入数字',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: undefined,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: undefined,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        min: 0,
        group: '基础',
      },
      {
        key: 'precision',
        label: '精度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'controls',
        label: '显示控制按钮',
        type: 'switch',
        defaultValue: true,
        group: '交互',
      },
      {
        key: 'controlsPosition',
        label: '控制按钮位置',
        type: 'select',
        defaultValue: '',
        options: [
          { label: '默认', value: '' },
          { label: '右侧', value: 'right' },
        ],
        group: '样式',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
];
