export default [
  {
    type: 'el-input',
    name: '输入框',
    category: 'form',
    properties: [
      {
        key: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '密码', value: 'password' },
          { label: '数字', value: 'number' },
          { label: '邮箱', value: 'email' },
          { label: 'URL', value: 'url' },
        ],
        group: '基础',
      },
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请输入内容',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'showPassword',
        label: '显示密码',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'maxlength',
        label: '最大长度',
        type: 'number',
        defaultValue: undefined,
        min: 0,
        placeholder: '不限制',
        group: '验证',
      },
      {
        key: 'showWordLimit',
        label: '显示字数统计',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
];
