export default [
  {
    type: 'el-select',
    name: '选择器',
    category: 'form',
    properties: [
      {
        key: 'placeholder',
        label: '占位符',
        type: 'input',
        defaultValue: '请选择',
        placeholder: '请输入占位符文本',
        group: '基础',
      },
      {
        key: 'options',
        label: '选项数据',
        type: 'json',
        defaultValue: [
          { label: '选项1', value: 'option1' },
          { label: '选项2', value: 'option2' },
          { label: '选项3', value: 'option3' },
        ],
        placeholder: '[{"label":"选项","value":"value"}]',
        description: '选项数组，如：[{"label":"选项1","value":"value1"}]',
        group: '数据',
      },
      {
        key: 'disabled',
        label: '禁用',
        type: 'switch',
        defaultValue: false,
        group: '状态',
      },
      {
        key: 'clearable',
        label: '可清空',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'multiple',
        label: '多选',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'filterable',
        label: '可搜索',
        type: 'switch',
        defaultValue: false,
        group: '交互',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '样式',
      },
      {
        key: 'style',
        label: '自定义样式',
        type: 'style',
        defaultValue: {},
        placeholder: '{}',
        description: 'CSS样式对象',
        group: '样式',
      },
    ],
  },
];
