#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 自动切换到 .nvmrc 指定的 Node.js 版本
if [ -f .nvmrc ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm use > /dev/null 2>&1 || true
fi

npm run lint-staged
